services:
  db:
    hostname: ${POSTGRES_HOST:-localhost}
    image: postgres:18.1
    container_name: docuisine-postgres-dev
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-docuisine}
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - docuisine_db_data:/var/lib/postgresql/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-user}",
          "-d",
          "${POSTGRES_DB:-docuisine}",
          "-h",
          "${POSTGRES_HOST:-localhost}",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: docuisine-minio-dev
    ports:
      - "${MINIO_S3_PORT:-9000}:9000" # S3 API
      - "${MINIO_CONSOLE_PORT:-9001}:9001" # Web Console
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    volumes:
      - docuisine_minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  # This service initializes the MinIO bucket and uploads initial images
  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: docuisine-minio-dev-init
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init-images:/init-images:ro
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${S3_ACCESS_KEY:-minioadmin} ${S3_SECRET_KEY:-minioadmin};

      mc mb local/${S3_BUCKET_NAME:-docuisine-images};

      mc anonymous set download local/${S3_BUCKET_NAME:-docuisine-images};

      mc cp /init-images/* local/${S3_BUCKET_NAME:-docuisine-images};

      exit 0;
      "
    restart: "no"

volumes:
  docuisine_db_data:
  docuisine_minio_data:
